-- Script para agregar jugadores del EC Bahia
-- Temporada 2025-2026
-- Fuente: Transfermarkt

-- Primero, asegurarse de que Bahia existe en DIM_EQUIPO
INSERT INTO DIM_EQUIPO (TEAM_ID_FBR, NOMBRE, APODO, CIUDAD, FECHA_FUNDACION)
SELECT 'bahia-br', 'Esporte Clube Bahia', 'Bahia', 'Salvador', '1931-01-01'
WHERE NOT EXISTS (
  SELECT 1 FROM DIM_EQUIPO WHERE NOMBRE = 'Esporte Clube Bahia'
);

-- Asegurar que las posiciones existen
INSERT IGNORE INTO DIM_POSICION (NOMBRE, DESCRIPCION) VALUES
('GK', 'Portero / Arquero'),
('CB', 'Defensa Central'),
('LB', 'Lateral Izquierdo'),
('RB', 'Lateral Derecho'),
('DM', 'Pivote / Mediocentro Defensivo'),
('CM', 'Mediocentro'),
('AM', 'Mediocentro Ofensivo'),
('LW', 'Extremo Izquierdo'),
('RW', 'Extremo Derecho'),
('CF', 'Delantero Centro');

-- Asegurar que los países existen
INSERT IGNORE INTO DIM_PAIS (CODIGO_FIFA, NOMBRE) VALUES
('BRA', 'Brasil'),
('ARG', 'Argentina'),
('URU', 'Uruguay'),
('ITA', 'Italia'),
('ESP', 'España'),
('GER', 'Alemania');

-- Insertar jugadores con IDs temporales de FBRef (formato: bahia-nombre)

-- PORTEROS
INSERT IGNORE INTO DIM_JUGADOR (PLAYER_ID_FBR, NOMBRE_COMPLETO, FECHA_NACIMIENTO)
VALUES ('bahia-joao-paulo', 'João Paulo', '1995-06-29');
INSERT IGNORE INTO DIM_JUGADOR_PAIS (ID_JUGADOR, ID_PAIS, ES_PAIS_PRIMARIO)
SELECT j.ID_JUGADOR, p.ID_PAIS, TRUE
FROM DIM_JUGADOR j, DIM_PAIS p
WHERE j.PLAYER_ID_FBR = 'bahia-joao-paulo' AND p.CODIGO_FIFA = 'BRA';
INSERT IGNORE INTO DIM_JUGADOR_POSICION (ID_JUGADOR, ID_POSICION, ES_POSICION_PRINCIPAL)
SELECT j.ID_JUGADOR, pos.ID_POSICION, TRUE
FROM DIM_JUGADOR j, DIM_POSICION pos
WHERE j.PLAYER_ID_FBR = 'bahia-joao-paulo' AND pos.NOMBRE = 'GK';

INSERT IGNORE INTO DIM_JUGADOR (PLAYER_ID_FBR, NOMBRE_COMPLETO, FECHA_NACIMIENTO)
VALUES ('bahia-ronaldo', 'Ronaldo', '1996-08-22');
INSERT IGNORE INTO DIM_JUGADOR_PAIS (ID_JUGADOR, ID_PAIS, ES_PAIS_PRIMARIO)
SELECT j.ID_JUGADOR, p.ID_PAIS, TRUE
FROM DIM_JUGADOR j, DIM_PAIS p
WHERE j.PLAYER_ID_FBR = 'bahia-ronaldo' AND p.CODIGO_FIFA = 'BRA';
INSERT IGNORE INTO DIM_JUGADOR_POSICION (ID_JUGADOR, ID_POSICION, ES_POSICION_PRINCIPAL)
SELECT j.ID_JUGADOR, pos.ID_POSICION, TRUE
FROM DIM_JUGADOR j, DIM_POSICION pos
WHERE j.PLAYER_ID_FBR = 'bahia-ronaldo' AND pos.NOMBRE = 'GK';

-- DEFENSAS CENTRALES
INSERT IGNORE INTO DIM_JUGADOR (PLAYER_ID_FBR, NOMBRE_COMPLETO, APODO, FECHA_NACIMIENTO)
VALUES ('bahia-santiago-ramos', 'Santiago Ramos Mingo', 'Santiago Ramos Mingo', '2001-11-21');
INSERT IGNORE INTO DIM_JUGADOR_PAIS (ID_JUGADOR, ID_PAIS, ES_PAIS_PRIMARIO)
SELECT j.ID_JUGADOR, p.ID_PAIS, TRUE
FROM DIM_JUGADOR j, DIM_PAIS p
WHERE j.PLAYER_ID_FBR = 'bahia-santiago-ramos' AND p.CODIGO_FIFA = 'ARG';
INSERT IGNORE INTO DIM_JUGADOR_PAIS (ID_JUGADOR, ID_PAIS, ES_PAIS_PRIMARIO)
SELECT j.ID_JUGADOR, p.ID_PAIS, FALSE
FROM DIM_JUGADOR j, DIM_PAIS p
WHERE j.PLAYER_ID_FBR = 'bahia-santiago-ramos' AND p.CODIGO_FIFA = 'ITA';
INSERT IGNORE INTO DIM_JUGADOR_POSICION (ID_JUGADOR, ID_POSICION, ES_POSICION_PRINCIPAL)
SELECT j.ID_JUGADOR, pos.ID_POSICION, TRUE
FROM DIM_JUGADOR j, DIM_POSICION pos
WHERE j.PLAYER_ID_FBR = 'bahia-santiago-ramos' AND pos.NOMBRE = 'CB';

INSERT IGNORE INTO DIM_JUGADOR (PLAYER_ID_FBR, NOMBRE_COMPLETO, APODO, FECHA_NACIMIENTO)
VALUES ('bahia-gabriel-xavier', 'Gabriel Xavier', 'Gabriel Xavier', '2001-05-06');
INSERT IGNORE INTO DIM_JUGADOR_PAIS (ID_JUGADOR, ID_PAIS, ES_PAIS_PRIMARIO)
SELECT j.ID_JUGADOR, p.ID_PAIS, TRUE FROM DIM_JUGADOR j, DIM_PAIS p
WHERE j.PLAYER_ID_FBR = 'bahia-gabriel-xavier' AND p.CODIGO_FIFA = 'BRA';
INSERT IGNORE INTO DIM_JUGADOR_POSICION (ID_JUGADOR, ID_POSICION, ES_POSICION_PRINCIPAL)
SELECT j.ID_JUGADOR, pos.ID_POSICION, TRUE FROM DIM_JUGADOR j, DIM_POSICION pos
WHERE j.PLAYER_ID_FBR = 'bahia-gabriel-xavier' AND pos.NOMBRE = 'CB';

INSERT IGNORE INTO DIM_JUGADOR (PLAYER_ID_FBR, NOMBRE_COMPLETO, APODO, FECHA_NACIMIENTO)
VALUES ('bahia-kanu', 'Kanu', 'Kanu', '1997-03-07');
INSERT IGNORE INTO DIM_JUGADOR_PAIS (ID_JUGADOR, ID_PAIS, ES_PAIS_PRIMARIO)
SELECT j.ID_JUGADOR, p.ID_PAIS, TRUE FROM DIM_JUGADOR j, DIM_PAIS p
WHERE j.PLAYER_ID_FBR = 'bahia-kanu' AND p.CODIGO_FIFA = 'BRA';
INSERT IGNORE INTO DIM_JUGADOR_POSICION (ID_JUGADOR, ID_POSICION, ES_POSICION_PRINCIPAL)
SELECT j.ID_JUGADOR, pos.ID_POSICION, TRUE FROM DIM_JUGADOR j, DIM_POSICION pos
WHERE j.PLAYER_ID_FBR = 'bahia-kanu' AND pos.NOMBRE = 'CB';

INSERT IGNORE INTO DIM_JUGADOR (PLAYER_ID_FBR, NOMBRE_COMPLETO, APODO, FECHA_NACIMIENTO)
VALUES ('bahia-david-duarte', 'David Duarte', 'David Duarte', '1995-01-24');
INSERT IGNORE INTO DIM_JUGADOR_PAIS (ID_JUGADOR, ID_PAIS, ES_PAIS_PRIMARIO)
SELECT j.ID_JUGADOR, p.ID_PAIS, TRUE FROM DIM_JUGADOR j, DIM_PAIS p
WHERE j.PLAYER_ID_FBR = 'bahia-david-duarte' AND p.CODIGO_FIFA = 'BRA';
INSERT IGNORE INTO DIM_JUGADOR_POSICION (ID_JUGADOR, ID_POSICION, ES_POSICION_PRINCIPAL)
SELECT j.ID_JUGADOR, pos.ID_POSICION, TRUE FROM DIM_JUGADOR j, DIM_POSICION pos
WHERE j.PLAYER_ID_FBR = 'bahia-david-duarte' AND pos.NOMBRE = 'CB';

INSERT IGNORE INTO DIM_JUGADOR (PLAYER_ID_FBR, NOMBRE_COMPLETO, APODO, FECHA_NACIMIENTO)
VALUES ('bahia-luiz-gustavo', 'Luiz Gustavo', 'Luiz Gustavo', '2006-04-12');
INSERT IGNORE INTO DIM_JUGADOR_PAIS (ID_JUGADOR, ID_PAIS, ES_PAIS_PRIMARIO)
SELECT j.ID_JUGADOR, p.ID_PAIS, TRUE FROM DIM_JUGADOR j, DIM_PAIS p
WHERE j.PLAYER_ID_FBR = 'bahia-luiz-gustavo' AND p.CODIGO_FIFA = 'BRA';
INSERT IGNORE INTO DIM_JUGADOR_POSICION (ID_JUGADOR, ID_POSICION, ES_POSICION_PRINCIPAL)
SELECT j.ID_JUGADOR, pos.ID_POSICION, TRUE FROM DIM_JUGADOR j, DIM_POSICION pos
WHERE j.PLAYER_ID_FBR = 'bahia-luiz-gustavo' AND pos.NOMBRE = 'CB';

-- LATERALES IZQUIERDOS
INSERT IGNORE INTO DIM_JUGADOR (PLAYER_ID_FBR, NOMBRE_COMPLETO, APODO, FECHA_NACIMIENTO)
VALUES ('bahia-luciano-juba', 'Luciano Juba', 'Luciano Juba', '1999-08-29');
INSERT IGNORE INTO DIM_JUGADOR_PAIS (ID_JUGADOR, ID_PAIS, ES_PAIS_PRIMARIO)
SELECT j.ID_JUGADOR, p.ID_PAIS, TRUE FROM DIM_JUGADOR j, DIM_PAIS p
WHERE j.PLAYER_ID_FBR = 'bahia-luciano-juba' AND p.CODIGO_FIFA = 'BRA';
INSERT IGNORE INTO DIM_JUGADOR_POSICION (ID_JUGADOR, ID_POSICION, ES_POSICION_PRINCIPAL)
SELECT j.ID_JUGADOR, pos.ID_POSICION, TRUE FROM DIM_JUGADOR j, DIM_POSICION pos
WHERE j.PLAYER_ID_FBR = 'bahia-luciano-juba' AND pos.NOMBRE = 'LB';

INSERT IGNORE INTO DIM_JUGADOR (PLAYER_ID_FBR, NOMBRE_COMPLETO, APODO, FECHA_NACIMIENTO)
VALUES ('bahia-iago', 'Iago', 'Iago', '1997-03-23');
INSERT IGNORE INTO DIM_JUGADOR_PAIS (ID_JUGADOR, ID_PAIS, ES_PAIS_PRIMARIO)
SELECT j.ID_JUGADOR, p.ID_PAIS, TRUE FROM DIM_JUGADOR j, DIM_PAIS p
WHERE j.PLAYER_ID_FBR = 'bahia-iago' AND p.CODIGO_FIFA = 'BRA';
INSERT IGNORE INTO DIM_JUGADOR_POSICION (ID_JUGADOR, ID_POSICION, ES_POSICION_PRINCIPAL)
SELECT j.ID_JUGADOR, pos.ID_POSICION, TRUE FROM DIM_JUGADOR j, DIM_POSICION pos
WHERE j.PLAYER_ID_FBR = 'bahia-iago' AND pos.NOMBRE = 'LB';

INSERT IGNORE INTO DIM_JUGADOR (PLAYER_ID_FBR, NOMBRE_COMPLETO, APODO, FECHA_NACIMIENTO)
VALUES ('bahia-matheus-bahia', 'Matheus Bahia', 'Matheus Bahia', '1999-08-11');
INSERT IGNORE INTO DIM_JUGADOR_PAIS (ID_JUGADOR, ID_PAIS, ES_PAIS_PRIMARIO)
SELECT j.ID_JUGADOR, p.ID_PAIS, TRUE FROM DIM_JUGADOR j, DIM_PAIS p
WHERE j.PLAYER_ID_FBR = 'bahia-matheus-bahia' AND p.CODIGO_FIFA = 'BRA';
INSERT IGNORE INTO DIM_JUGADOR_POSICION (ID_JUGADOR, ID_POSICION, ES_POSICION_PRINCIPAL)
SELECT j.ID_JUGADOR, pos.ID_POSICION, TRUE FROM DIM_JUGADOR j, DIM_POSICION pos
WHERE j.PLAYER_ID_FBR = 'bahia-matheus-bahia' AND pos.NOMBRE = 'LB';

INSERT IGNORE INTO DIM_JUGADOR (PLAYER_ID_FBR, NOMBRE_COMPLETO, APODO, FECHA_NACIMIENTO)
VALUES ('bahia-ze-guilherme', 'Zé Guilherme', 'Zé Guilherme', '2005-03-16');
INSERT IGNORE INTO DIM_JUGADOR_PAIS (ID_JUGADOR, ID_PAIS, ES_PAIS_PRIMARIO)
SELECT j.ID_JUGADOR, p.ID_PAIS, TRUE FROM DIM_JUGADOR j, DIM_PAIS p
WHERE j.PLAYER_ID_FBR = 'bahia-ze-guilherme' AND p.CODIGO_FIFA = 'BRA';
INSERT IGNORE INTO DIM_JUGADOR_POSICION (ID_JUGADOR, ID_POSICION, ES_POSICION_PRINCIPAL)
SELECT j.ID_JUGADOR, pos.ID_POSICION, TRUE FROM DIM_JUGADOR j, DIM_POSICION pos
WHERE j.PLAYER_ID_FBR = 'bahia-ze-guilherme' AND pos.NOMBRE = 'LB';

-- LATERALES DERECHOS
INSERT IGNORE INTO DIM_JUGADOR (PLAYER_ID_FBR, NOMBRE_COMPLETO, APODO, FECHA_NACIMIENTO)
VALUES ('bahia-gilberto', 'Gilberto', 'Gilberto', '1993-03-07');
INSERT IGNORE INTO DIM_JUGADOR_PAIS (ID_JUGADOR, ID_PAIS, ES_PAIS_PRIMARIO)
SELECT j.ID_JUGADOR, p.ID_PAIS, TRUE FROM DIM_JUGADOR j, DIM_PAIS p
WHERE j.PLAYER_ID_FBR = 'bahia-gilberto' AND p.CODIGO_FIFA = 'BRA';
INSERT IGNORE INTO DIM_JUGADOR_POSICION (ID_JUGADOR, ID_POSICION, ES_POSICION_PRINCIPAL)
SELECT j.ID_JUGADOR, pos.ID_POSICION, TRUE FROM DIM_JUGADOR j, DIM_POSICION pos
WHERE j.PLAYER_ID_FBR = 'bahia-gilberto' AND pos.NOMBRE = 'RB';

INSERT IGNORE INTO DIM_JUGADOR (PLAYER_ID_FBR, NOMBRE_COMPLETO, APODO, FECHA_NACIMIENTO)
VALUES ('bahia-roman-gomez', 'Román Gómez', 'Román Gómez', '2004-07-14');
INSERT IGNORE INTO DIM_JUGADOR_PAIS (ID_JUGADOR, ID_PAIS, ES_PAIS_PRIMARIO)
SELECT j.ID_JUGADOR, p.ID_PAIS, TRUE FROM DIM_JUGADOR j, DIM_PAIS p
WHERE j.PLAYER_ID_FBR = 'bahia-roman-gomez' AND p.CODIGO_FIFA = 'ARG';
INSERT IGNORE INTO DIM_JUGADOR_POSICION (ID_JUGADOR, ID_POSICION, ES_POSICION_PRINCIPAL)
SELECT j.ID_JUGADOR, pos.ID_POSICION, TRUE FROM DIM_JUGADOR j, DIM_POSICION pos
WHERE j.PLAYER_ID_FBR = 'bahia-roman-gomez' AND pos.NOMBRE = 'RB';

-- PIVOTES
INSERT IGNORE INTO DIM_JUGADOR (PLAYER_ID_FBR, NOMBRE_COMPLETO, APODO, FECHA_NACIMIENTO)
VALUES ('bahia-caio-alexandre', 'Caio Alexandre', 'Caio Alexandre', '1999-02-24');
INSERT IGNORE INTO DIM_JUGADOR_PAIS (ID_JUGADOR, ID_PAIS, ES_PAIS_PRIMARIO)
SELECT j.ID_JUGADOR, p.ID_PAIS, TRUE FROM DIM_JUGADOR j, DIM_PAIS p
WHERE j.PLAYER_ID_FBR = 'bahia-caio-alexandre' AND p.CODIGO_FIFA = 'BRA';
INSERT IGNORE INTO DIM_JUGADOR_POSICION (ID_JUGADOR, ID_POSICION, ES_POSICION_PRINCIPAL)
SELECT j.ID_JUGADOR, pos.ID_POSICION, TRUE FROM DIM_JUGADOR j, DIM_POSICION pos
WHERE j.PLAYER_ID_FBR = 'bahia-caio-alexandre' AND pos.NOMBRE = 'DM';

INSERT IGNORE INTO DIM_JUGADOR (PLAYER_ID_FBR, NOMBRE_COMPLETO, APODO, FECHA_NACIMIENTO)
VALUES ('bahia-erick-dm', 'Erick', 'Erick', '1997-11-14');
INSERT IGNORE INTO DIM_JUGADOR_PAIS (ID_JUGADOR, ID_PAIS, ES_PAIS_PRIMARIO)
SELECT j.ID_JUGADOR, p.ID_PAIS, TRUE FROM DIM_JUGADOR j, DIM_PAIS p
WHERE j.PLAYER_ID_FBR = 'bahia-erick-dm' AND p.CODIGO_FIFA = 'BRA';
INSERT IGNORE INTO DIM_JUGADOR_POSICION (ID_JUGADOR, ID_POSICION, ES_POSICION_PRINCIPAL)
SELECT j.ID_JUGADOR, pos.ID_POSICION, TRUE FROM DIM_JUGADOR j, DIM_POSICION pos
WHERE j.PLAYER_ID_FBR = 'bahia-erick-dm' AND pos.NOMBRE = 'DM';

INSERT IGNORE INTO DIM_JUGADOR (PLAYER_ID_FBR, NOMBRE_COMPLETO, APODO, FECHA_NACIMIENTO)
VALUES ('bahia-nicolas-acevedo', 'Nicolás Acevedo', 'Nicolás Acevedo', '1999-04-14');
INSERT IGNORE INTO DIM_JUGADOR_PAIS (ID_JUGADOR, ID_PAIS, ES_PAIS_PRIMARIO)
SELECT j.ID_JUGADOR, p.ID_PAIS, TRUE FROM DIM_JUGADOR j, DIM_PAIS p
WHERE j.PLAYER_ID_FBR = 'bahia-nicolas-acevedo' AND p.CODIGO_FIFA = 'URU';
INSERT IGNORE INTO DIM_JUGADOR_POSICION (ID_JUGADOR, ID_POSICION, ES_POSICION_PRINCIPAL)
SELECT j.ID_JUGADOR, pos.ID_POSICION, TRUE FROM DIM_JUGADOR j, DIM_POSICION pos
WHERE j.PLAYER_ID_FBR = 'bahia-nicolas-acevedo' AND pos.NOMBRE = 'DM';

INSERT IGNORE INTO DIM_JUGADOR (PLAYER_ID_FBR, NOMBRE_COMPLETO, APODO, FECHA_NACIMIENTO)
VALUES ('bahia-rezende', 'Rezende', 'Rezende', '1995-01-02');
INSERT IGNORE INTO DIM_JUGADOR_PAIS (ID_JUGADOR, ID_PAIS, ES_PAIS_PRIMARIO)
SELECT j.ID_JUGADOR, p.ID_PAIS, TRUE FROM DIM_JUGADOR j, DIM_PAIS p
WHERE j.PLAYER_ID_FBR = 'bahia-rezende' AND p.CODIGO_FIFA = 'BRA';
INSERT IGNORE INTO DIM_JUGADOR_POSICION (ID_JUGADOR, ID_POSICION, ES_POSICION_PRINCIPAL)
SELECT j.ID_JUGADOR, pos.ID_POSICION, TRUE FROM DIM_JUGADOR j, DIM_POSICION pos
WHERE j.PLAYER_ID_FBR = 'bahia-rezende' AND pos.NOMBRE = 'DM';

-- MEDIOCENTROS
INSERT IGNORE INTO DIM_JUGADOR (PLAYER_ID_FBR, NOMBRE_COMPLETO, APODO, FECHA_NACIMIENTO)
VALUES ('bahia-jean-lucas', 'Jean Lucas', 'Jean Lucas', '1998-06-22');
INSERT IGNORE INTO DIM_JUGADOR_PAIS (ID_JUGADOR, ID_PAIS, ES_PAIS_PRIMARIO)
SELECT j.ID_JUGADOR, p.ID_PAIS, TRUE FROM DIM_JUGADOR j, DIM_PAIS p
WHERE j.PLAYER_ID_FBR = 'bahia-jean-lucas' AND p.CODIGO_FIFA = 'BRA';
INSERT IGNORE INTO DIM_JUGADOR_POSICION (ID_JUGADOR, ID_POSICION, ES_POSICION_PRINCIPAL)
SELECT j.ID_JUGADOR, pos.ID_POSICION, TRUE FROM DIM_JUGADOR j, DIM_POSICION pos
WHERE j.PLAYER_ID_FBR = 'bahia-jean-lucas' AND pos.NOMBRE = 'CM';

INSERT IGNORE INTO DIM_JUGADOR (PLAYER_ID_FBR, NOMBRE_COMPLETO, APODO, FECHA_NACIMIENTO)
VALUES ('bahia-rodrigo-nestor', 'Rodrigo Nestor', 'Rodrigo Nestor', '2000-08-09');
INSERT IGNORE INTO DIM_JUGADOR_PAIS (ID_JUGADOR, ID_PAIS, ES_PAIS_PRIMARIO)
SELECT j.ID_JUGADOR, p.ID_PAIS, TRUE FROM DIM_JUGADOR j, DIM_PAIS p
WHERE j.PLAYER_ID_FBR = 'bahia-rodrigo-nestor' AND p.CODIGO_FIFA = 'BRA';
INSERT IGNORE INTO DIM_JUGADOR_POSICION (ID_JUGADOR, ID_POSICION, ES_POSICION_PRINCIPAL)
SELECT j.ID_JUGADOR, pos.ID_POSICION, TRUE FROM DIM_JUGADOR j, DIM_POSICION pos
WHERE j.PLAYER_ID_FBR = 'bahia-rodrigo-nestor' AND pos.NOMBRE = 'CM';

INSERT IGNORE INTO DIM_JUGADOR (PLAYER_ID_FBR, NOMBRE_COMPLETO, APODO, FECHA_NACIMIENTO)
VALUES ('bahia-miqueias', 'Miqueias', 'Miqueias', '2001-07-27');
INSERT IGNORE INTO DIM_JUGADOR_PAIS (ID_JUGADOR, ID_PAIS, ES_PAIS_PRIMARIO)
SELECT j.ID_JUGADOR, p.ID_PAIS, TRUE FROM DIM_JUGADOR j, DIM_PAIS p
WHERE j.PLAYER_ID_FBR = 'bahia-miqueias' AND p.CODIGO_FIFA = 'BRA';
INSERT IGNORE INTO DIM_JUGADOR_POSICION (ID_JUGADOR, ID_POSICION, ES_POSICION_PRINCIPAL)
SELECT j.ID_JUGADOR, pos.ID_POSICION, TRUE FROM DIM_JUGADOR j, DIM_POSICION pos
WHERE j.PLAYER_ID_FBR = 'bahia-miqueias' AND pos.NOMBRE = 'CM';

INSERT IGNORE INTO DIM_JUGADOR (PLAYER_ID_FBR, NOMBRE_COMPLETO, APODO, FECHA_NACIMIENTO)
VALUES ('bahia-jota', 'Jota', 'Jota', '2004-02-06');
INSERT IGNORE INTO DIM_JUGADOR_PAIS (ID_JUGADOR, ID_PAIS, ES_PAIS_PRIMARIO)
SELECT j.ID_JUGADOR, p.ID_PAIS, TRUE FROM DIM_JUGADOR j, DIM_PAIS p
WHERE j.PLAYER_ID_FBR = 'bahia-jota' AND p.CODIGO_FIFA = 'BRA';
INSERT IGNORE INTO DIM_JUGADOR_POSICION (ID_JUGADOR, ID_POSICION, ES_POSICION_PRINCIPAL)
SELECT j.ID_JUGADOR, pos.ID_POSICION, TRUE FROM DIM_JUGADOR j, DIM_POSICION pos
WHERE j.PLAYER_ID_FBR = 'bahia-jota' AND pos.NOMBRE = 'CM';

-- MEDIOCENTROS OFENSIVOS
INSERT IGNORE INTO DIM_JUGADOR (PLAYER_ID_FBR, NOMBRE_COMPLETO, APODO, FECHA_NACIMIENTO)
VALUES ('bahia-cauly', 'Cauly', 'Cauly', '1995-09-15');
INSERT IGNORE INTO DIM_JUGADOR_PAIS (ID_JUGADOR, ID_PAIS, ES_PAIS_PRIMARIO)
SELECT j.ID_JUGADOR, p.ID_PAIS, TRUE FROM DIM_JUGADOR j, DIM_PAIS p
WHERE j.PLAYER_ID_FBR = 'bahia-cauly' AND p.CODIGO_FIFA = 'BRA';
INSERT IGNORE INTO DIM_JUGADOR_PAIS (ID_JUGADOR, ID_PAIS, ES_PAIS_PRIMARIO)
SELECT j.ID_JUGADOR, p.ID_PAIS, FALSE FROM DIM_JUGADOR j, DIM_PAIS p
WHERE j.PLAYER_ID_FBR = 'bahia-cauly' AND p.CODIGO_FIFA = 'GER';
INSERT IGNORE INTO DIM_JUGADOR_POSICION (ID_JUGADOR, ID_POSICION, ES_POSICION_PRINCIPAL)
SELECT j.ID_JUGADOR, pos.ID_POSICION, TRUE FROM DIM_JUGADOR j, DIM_POSICION pos
WHERE j.PLAYER_ID_FBR = 'bahia-cauly' AND pos.NOMBRE = 'AM';

INSERT IGNORE INTO DIM_JUGADOR (PLAYER_ID_FBR, NOMBRE_COMPLETO, APODO, FECHA_NACIMIENTO)
VALUES ('bahia-everton-ribeiro', 'Everton Ribeiro', 'Everton Ribeiro', '1989-04-10');
INSERT IGNORE INTO DIM_JUGADOR_PAIS (ID_JUGADOR, ID_PAIS, ES_PAIS_PRIMARIO)
SELECT j.ID_JUGADOR, p.ID_PAIS, TRUE FROM DIM_JUGADOR j, DIM_PAIS p
WHERE j.PLAYER_ID_FBR = 'bahia-everton-ribeiro' AND p.CODIGO_FIFA = 'BRA';
INSERT IGNORE INTO DIM_JUGADOR_POSICION (ID_JUGADOR, ID_POSICION, ES_POSICION_PRINCIPAL)
SELECT j.ID_JUGADOR, pos.ID_POSICION, TRUE FROM DIM_JUGADOR j, DIM_POSICION pos
WHERE j.PLAYER_ID_FBR = 'bahia-everton-ribeiro' AND pos.NOMBRE = 'AM';

-- EXTREMOS IZQUIERDOS
INSERT IGNORE INTO DIM_JUGADOR (PLAYER_ID_FBR, NOMBRE_COMPLETO, APODO, FECHA_NACIMIENTO)
VALUES ('bahia-erick-pulga', 'Erick Pulga', 'Erick Pulga', '2000-10-02');
INSERT IGNORE INTO DIM_JUGADOR_PAIS (ID_JUGADOR, ID_PAIS, ES_PAIS_PRIMARIO)
SELECT j.ID_JUGADOR, p.ID_PAIS, TRUE FROM DIM_JUGADOR j, DIM_PAIS p
WHERE j.PLAYER_ID_FBR = 'bahia-erick-pulga' AND p.CODIGO_FIFA = 'BRA';
INSERT IGNORE INTO DIM_JUGADOR_POSICION (ID_JUGADOR, ID_POSICION, ES_POSICION_PRINCIPAL)
SELECT j.ID_JUGADOR, pos.ID_POSICION, TRUE FROM DIM_JUGADOR j, DIM_POSICION pos
WHERE j.PLAYER_ID_FBR = 'bahia-erick-pulga' AND pos.NOMBRE = 'LW';

INSERT IGNORE INTO DIM_JUGADOR (PLAYER_ID_FBR, NOMBRE_COMPLETO, APODO, FECHA_NACIMIENTO)
VALUES ('bahia-ruan-pablo', 'Ruan Pablo', 'Ruan Pablo', '2008-07-23');
INSERT IGNORE INTO DIM_JUGADOR_PAIS (ID_JUGADOR, ID_PAIS, ES_PAIS_PRIMARIO)
SELECT j.ID_JUGADOR, p.ID_PAIS, TRUE FROM DIM_JUGADOR j, DIM_PAIS p
WHERE j.PLAYER_ID_FBR = 'bahia-ruan-pablo' AND p.CODIGO_FIFA = 'BRA';
INSERT IGNORE INTO DIM_JUGADOR_POSICION (ID_JUGADOR, ID_POSICION, ES_POSICION_PRINCIPAL)
SELECT j.ID_JUGADOR, pos.ID_POSICION, TRUE FROM DIM_JUGADOR j, DIM_POSICION pos
WHERE j.PLAYER_ID_FBR = 'bahia-ruan-pablo' AND pos.NOMBRE = 'LW';

INSERT IGNORE INTO DIM_JUGADOR (PLAYER_ID_FBR, NOMBRE_COMPLETO, APODO, FECHA_NACIMIENTO)
VALUES ('bahia-michel-araujo', 'Michel Araújo', 'Michel Araújo', '1996-09-28');
INSERT IGNORE INTO DIM_JUGADOR_PAIS (ID_JUGADOR, ID_PAIS, ES_PAIS_PRIMARIO)
SELECT j.ID_JUGADOR, p.ID_PAIS, TRUE FROM DIM_JUGADOR j, DIM_PAIS p
WHERE j.PLAYER_ID_FBR = 'bahia-michel-araujo' AND p.CODIGO_FIFA = 'URU';
INSERT IGNORE INTO DIM_JUGADOR_POSICION (ID_JUGADOR, ID_POSICION, ES_POSICION_PRINCIPAL)
SELECT j.ID_JUGADOR, pos.ID_POSICION, TRUE FROM DIM_JUGADOR j, DIM_POSICION pos
WHERE j.PLAYER_ID_FBR = 'bahia-michel-araujo' AND pos.NOMBRE = 'LW';

INSERT IGNORE INTO DIM_JUGADOR (PLAYER_ID_FBR, NOMBRE_COMPLETO, APODO, FECHA_NACIMIENTO)
VALUES ('bahia-mateo-sanabria', 'Mateo Sanabria', 'Mateo Sanabria', '2004-03-31');
INSERT IGNORE INTO DIM_JUGADOR_PAIS (ID_JUGADOR, ID_PAIS, ES_PAIS_PRIMARIO)
SELECT j.ID_JUGADOR, p.ID_PAIS, TRUE FROM DIM_JUGADOR j, DIM_PAIS p
WHERE j.PLAYER_ID_FBR = 'bahia-mateo-sanabria' AND p.CODIGO_FIFA = 'ARG';
INSERT IGNORE INTO DIM_JUGADOR_PAIS (ID_JUGADOR, ID_PAIS, ES_PAIS_PRIMARIO)
SELECT j.ID_JUGADOR, p.ID_PAIS, FALSE FROM DIM_JUGADOR j, DIM_PAIS p
WHERE j.PLAYER_ID_FBR = 'bahia-mateo-sanabria' AND p.CODIGO_FIFA = 'ITA';
INSERT IGNORE INTO DIM_JUGADOR_POSICION (ID_JUGADOR, ID_POSICION, ES_POSICION_PRINCIPAL)
SELECT j.ID_JUGADOR, pos.ID_POSICION, TRUE FROM DIM_JUGADOR j, DIM_POSICION pos
WHERE j.PLAYER_ID_FBR = 'bahia-mateo-sanabria' AND pos.NOMBRE = 'LW';

-- EXTREMOS DERECHOS
INSERT IGNORE INTO DIM_JUGADOR (PLAYER_ID_FBR, NOMBRE_COMPLETO, APODO, FECHA_NACIMIENTO)
VALUES ('bahia-cristian-olivera', 'Cristian Olivera', 'Cristian Olivera', '2002-04-17');
INSERT IGNORE INTO DIM_JUGADOR_PAIS (ID_JUGADOR, ID_PAIS, ES_PAIS_PRIMARIO)
SELECT j.ID_JUGADOR, p.ID_PAIS, TRUE FROM DIM_JUGADOR j, DIM_PAIS p
WHERE j.PLAYER_ID_FBR = 'bahia-cristian-olivera' AND p.CODIGO_FIFA = 'URU';
INSERT IGNORE INTO DIM_JUGADOR_POSICION (ID_JUGADOR, ID_POSICION, ES_POSICION_PRINCIPAL)
SELECT j.ID_JUGADOR, pos.ID_POSICION, TRUE FROM DIM_JUGADOR j, DIM_POSICION pos
WHERE j.PLAYER_ID_FBR = 'bahia-cristian-olivera' AND pos.NOMBRE = 'RW';

INSERT IGNORE INTO DIM_JUGADOR (PLAYER_ID_FBR, NOMBRE_COMPLETO, APODO, FECHA_NACIMIENTO)
VALUES ('bahia-ademir', 'Ademir', 'Ademir', '1995-02-16');
INSERT IGNORE INTO DIM_JUGADOR_PAIS (ID_JUGADOR, ID_PAIS, ES_PAIS_PRIMARIO)
SELECT j.ID_JUGADOR, p.ID_PAIS, TRUE FROM DIM_JUGADOR j, DIM_PAIS p
WHERE j.PLAYER_ID_FBR = 'bahia-ademir' AND p.CODIGO_FIFA = 'BRA';
INSERT IGNORE INTO DIM_JUGADOR_POSICION (ID_JUGADOR, ID_POSICION, ES_POSICION_PRINCIPAL)
SELECT j.ID_JUGADOR, pos.ID_POSICION, TRUE FROM DIM_JUGADOR j, DIM_POSICION pos
WHERE j.PLAYER_ID_FBR = 'bahia-ademir' AND pos.NOMBRE = 'RW';

-- DELANTEROS CENTRO
INSERT IGNORE INTO DIM_JUGADOR (PLAYER_ID_FBR, NOMBRE_COMPLETO, APODO, FECHA_NACIMIENTO)
VALUES ('bahia-willian-jose', 'Willian José', 'Willian José', '1991-11-23');
INSERT IGNORE INTO DIM_JUGADOR_PAIS (ID_JUGADOR, ID_PAIS, ES_PAIS_PRIMARIO)
SELECT j.ID_JUGADOR, p.ID_PAIS, TRUE FROM DIM_JUGADOR j, DIM_PAIS p
WHERE j.PLAYER_ID_FBR = 'bahia-willian-jose' AND p.CODIGO_FIFA = 'BRA';
INSERT IGNORE INTO DIM_JUGADOR_PAIS (ID_JUGADOR, ID_PAIS, ES_PAIS_PRIMARIO)
SELECT j.ID_JUGADOR, p.ID_PAIS, FALSE FROM DIM_JUGADOR j, DIM_PAIS p
WHERE j.PLAYER_ID_FBR = 'bahia-willian-jose' AND p.CODIGO_FIFA = 'ESP';
INSERT IGNORE INTO DIM_JUGADOR_POSICION (ID_JUGADOR, ID_POSICION, ES_POSICION_PRINCIPAL)
SELECT j.ID_JUGADOR, pos.ID_POSICION, TRUE FROM DIM_JUGADOR j, DIM_POSICION pos
WHERE j.PLAYER_ID_FBR = 'bahia-willian-jose' AND pos.NOMBRE = 'CF';

INSERT IGNORE INTO DIM_JUGADOR (PLAYER_ID_FBR, NOMBRE_COMPLETO, APODO, FECHA_NACIMIENTO)
VALUES ('bahia-everaldo', 'Everaldo', 'Everaldo', '1991-07-05');
INSERT IGNORE INTO DIM_JUGADOR_PAIS (ID_JUGADOR, ID_PAIS, ES_PAIS_PRIMARIO)
SELECT j.ID_JUGADOR, p.ID_PAIS, TRUE FROM DIM_JUGADOR j, DIM_PAIS p
WHERE j.PLAYER_ID_FBR = 'bahia-everaldo' AND p.CODIGO_FIFA = 'BRA';
INSERT IGNORE INTO DIM_JUGADOR_POSICION (ID_JUGADOR, ID_POSICION, ES_POSICION_PRINCIPAL)
SELECT j.ID_JUGADOR, pos.ID_POSICION, TRUE FROM DIM_JUGADOR j, DIM_POSICION pos
WHERE j.PLAYER_ID_FBR = 'bahia-everaldo' AND pos.NOMBRE = 'CF';

INSERT IGNORE INTO DIM_JUGADOR (PLAYER_ID_FBR, NOMBRE_COMPLETO, APODO, FECHA_NACIMIENTO)
VALUES ('bahia-dell', 'Dell', 'Dell', '2008-06-09');
INSERT IGNORE INTO DIM_JUGADOR_PAIS (ID_JUGADOR, ID_PAIS, ES_PAIS_PRIMARIO)
SELECT j.ID_JUGADOR, p.ID_PAIS, TRUE FROM DIM_JUGADOR j, DIM_PAIS p
WHERE j.PLAYER_ID_FBR = 'bahia-dell' AND p.CODIGO_FIFA = 'BRA';
INSERT IGNORE INTO DIM_JUGADOR_POSICION (ID_JUGADOR, ID_POSICION, ES_POSICION_PRINCIPAL)
SELECT j.ID_JUGADOR, pos.ID_POSICION, TRUE FROM DIM_JUGADOR j, DIM_POSICION pos
WHERE j.PLAYER_ID_FBR = 'bahia-dell' AND pos.NOMBRE = 'CF';

-- Mensaje final
SELECT '✅ Jugadores de Bahia agregados exitosamente' as mensaje;
SELECT COUNT(*) as total_jugadores_bahia FROM DIM_JUGADOR WHERE PLAYER_ID_FBR LIKE 'bahia-%';
