-- Script para agregar jugadores del EC Bahia
-- Temporada 2025-2026
-- Fuente: Transfermarkt

-- Primero, asegurarse de que Bahia existe en DIM_EQUIPO
-- Si no existe, crear el equipo (TEAM_ID_FBR puede ser el ID de Bahia en FBRef o un valor único temporal)
INSERT INTO DIM_EQUIPO (TEAM_ID_FBR, NOMBRE, APODO, CIUDAD, FECHA_FUNDACION)
SELECT 'bahia-br', 'Esporte Clube Bahia', 'Bahia', 'Salvador', '1931-01-01'
WHERE NOT EXISTS (
  SELECT 1 FROM DIM_EQUIPO WHERE NOMBRE = 'Esporte Clube Bahia'
);

-- Variable para el ID de Bahia
SET @id_bahia = (SELECT ID_EQUIPO FROM DIM_EQUIPO WHERE NOMBRE = 'Esporte Clube Bahia' LIMIT 1);

-- Asegurar que las posiciones existen
INSERT IGNORE INTO DIM_POSICION (NOMBRE, DESCRIPCION) VALUES
('GK', 'Portero / Arquero'),
('CB', 'Defensa Central'),
('LB', 'Lateral Izquierdo'),
('RB', 'Lateral Derecho'),
('DM', 'Pivote / Mediocentro Defensivo'),
('CM', 'Mediocentro'),
('AM', 'Mediocentro Ofensivo'),
('LW', 'Extremo Izquierdo'),
('RW', 'Extremo Derecho'),
('CF', 'Delantero Centro');

-- Asegurar que los países existen (NOMBRE es el nombre completo, CODIGO_FIFA es el código)
INSERT IGNORE INTO DIM_PAIS (CODIGO_FIFA, NOMBRE) VALUES
('BRA', 'Brasil'),
('ARG', 'Argentina'),
('URU', 'Uruguay'),
('ITA', 'Italia'),
('ESP', 'España'),
('GER', 'Alemania');

-- ========================================
-- PORTEROS
-- ========================================

-- João Paulo (GK) - 29/06/1995 (30 años) - Brasil - 2.00 mill. €
INSERT INTO DIM_JUGADOR (NOMBRE_COMPLETO, FECHA_NACIMIENTO, PLAYER_ID_FBR)
VALUES ('João Paulo', '1995-06-29', NULL);
SET @id_joao_paulo = LAST_INSERT_ID();

INSERT IGNORE INTO DIM_JUGADOR_PAIS (ID_JUGADOR, ID_PAIS, ES_PAIS_PRIMARIO)
VALUES (@id_joao_paulo, (SELECT ID_PAIS FROM DIM_PAIS WHERE CODIGO_FIFA = 'BRA'), TRUE);

INSERT IGNORE INTO DIM_JUGADOR_POSICION (ID_JUGADOR, ID_POSICION, ES_POSICION_PRINCIPAL)
VALUES (@id_joao_paulo, (SELECT ID_POSICION FROM DIM_POSICION WHERE NOMBRE = 'GK'), TRUE);

-- Ronaldo (GK) - 22/08/1996 (29 años) - Brasil - 1.80 mill. € - #21
INSERT INTO DIM_JUGADOR (NOMBRE_COMPLETO, FECHA_NACIMIENTO, PLAYER_ID_FBR)
VALUES ('Ronaldo', '1996-08-22', NULL);
SET @id_ronaldo = LAST_INSERT_ID();

INSERT IGNORE INTO DIM_JUGADOR_PAIS (ID_JUGADOR, ID_PAIS, ES_PAIS_PRIMARIO)
VALUES (@id_ronaldo, (SELECT ID_PAIS FROM DIM_PAIS WHERE CODIGO_FIFA = 'BRA'), TRUE);

INSERT IGNORE INTO DIM_JUGADOR_POSICION (ID_JUGADOR, ID_POSICION, ES_POSICION_PRINCIPAL)
VALUES (@id_ronaldo, (SELECT ID_POSICION FROM DIM_POSICION WHERE NOMBRE = 'GK'), TRUE);

-- ========================================
-- DEFENSAS CENTRALES
-- ========================================

-- Santiago Ramos Mingo (CB) - 21/11/2001 (24 años) - Argentina/Italia - 11.00 mill. € - #3
INSERT INTO DIM_JUGADOR (NOMBRE_COMPLETO, APODO, FECHA_NACIMIENTO, PLAYER_ID_FBR)
VALUES ('Santiago Ramos Mingo', 'Santiago Ramos Mingo', '2001-11-21', NULL);
SET @id_santiago = LAST_INSERT_ID();

INSERT IGNORE INTO DIM_JUGADOR_PAIS (ID_JUGADOR, ID_PAIS, ES_PAIS_PRIMARIO)
VALUES (@id_santiago, (SELECT ID_PAIS FROM DIM_PAIS WHERE CODIGO_FIFA = 'ARG'), TRUE);
INSERT IGNORE INTO DIM_JUGADOR_PAIS (ID_JUGADOR, ID_PAIS, ES_PAIS_PRIMARIO)
VALUES (@id_santiago, (SELECT ID_PAIS FROM DIM_PAIS WHERE CODIGO_FIFA = 'ITA'), FALSE);

INSERT IGNORE INTO DIM_JUGADOR_POSICION (ID_JUGADOR, ID_POSICION, ES_POSICION_PRINCIPAL)
VALUES (@id_santiago, (SELECT ID_POSICION FROM DIM_POSICION WHERE NOMBRE = 'CB'), TRUE);

-- Gabriel Xavier (CB) - 06/05/2001 (24 años) - Brasil - 4.00 mill. € - #4
INSERT INTO DIM_JUGADOR (NOMBRE_COMPLETO, APODO, FECHA_NACIMIENTO, PLAYER_ID_FBR)
VALUES ('Gabriel Xavier', 'Gabriel Xavier', '2001-05-06', NULL);
SET @id_gabriel_xavier = LAST_INSERT_ID();

INSERT IGNORE INTO DIM_JUGADOR_PAIS (ID_JUGADOR, ID_PAIS, ES_PAIS_PRIMARIO)
VALUES (@id_gabriel_xavier, (SELECT ID_PAIS FROM DIM_PAIS WHERE CODIGO_FIFA = 'BRA'), TRUE);

INSERT IGNORE INTO DIM_JUGADOR_POSICION (ID_JUGADOR, ID_POSICION, ES_POSICION_PRINCIPAL)
VALUES (@id_gabriel_xavier, (SELECT ID_POSICION FROM DIM_POSICION WHERE NOMBRE = 'CB'), TRUE);

-- Kanu (CB) - 07/03/1997 (28 años) - Brasil - 3.00 mill. € - #33
INSERT INTO DIM_JUGADOR (NOMBRE_COMPLETO, APODO, FECHA_NACIMIENTO, PLAYER_ID_FBR)
VALUES ('Kanu', 'Kanu', '1997-03-07', NULL);
SET @id_kanu = LAST_INSERT_ID();

INSERT IGNORE INTO DIM_JUGADOR_PAIS (ID_JUGADOR, ID_PAIS, ES_PAIS_PRIMARIO)
VALUES (@id_kanu, (SELECT ID_PAIS FROM DIM_PAIS WHERE CODIGO_FIFA = 'BRA'), TRUE);

INSERT IGNORE INTO DIM_JUGADOR_POSICION (ID_JUGADOR, ID_POSICION, ES_POSICION_PRINCIPAL)
VALUES (@id_kanu, (SELECT ID_POSICION FROM DIM_POSICION WHERE NOMBRE = 'CB'), TRUE);

-- David Duarte (CB) - 24/01/1995 (31 años) - Brasil - 1.20 mill. € - #43
INSERT INTO DIM_JUGADOR (NOMBRE_COMPLETO, APODO, FECHA_NACIMIENTO, PLAYER_ID_FBR)
VALUES ('David Duarte', 'David Duarte', '1995-01-24', NULL);
SET @id_david_duarte = LAST_INSERT_ID();

INSERT IGNORE INTO DIM_JUGADOR_PAIS (ID_JUGADOR, ID_PAIS, ES_PAIS_PRIMARIO)
VALUES (@id_david_duarte, (SELECT ID_PAIS FROM DIM_PAIS WHERE CODIGO_FIFA = 'BRA'), TRUE);

INSERT IGNORE INTO DIM_JUGADOR_POSICION (ID_JUGADOR, ID_POSICION, ES_POSICION_PRINCIPAL)
VALUES (@id_david_duarte, (SELECT ID_POSICION FROM DIM_POSICION WHERE NOMBRE = 'CB'), TRUE);

-- Luiz Gustavo (CB) - 12/04/2006 (19 años) - Brasil - 300 mil € - #46
INSERT INTO DIM_JUGADOR (NOMBRE_COMPLETO, APODO, FECHA_NACIMIENTO, PLAYER_ID_FBR)
VALUES ('Luiz Gustavo', 'Luiz Gustavo', '2006-04-12', NULL);
SET @id_luiz_gustavo = LAST_INSERT_ID();

INSERT IGNORE INTO DIM_JUGADOR_PAIS (ID_JUGADOR, ID_PAIS, ES_PAIS_PRIMARIO)
VALUES (@id_luiz_gustavo, (SELECT ID_PAIS FROM DIM_PAIS WHERE CODIGO_FIFA = 'BRA'), TRUE);

INSERT IGNORE INTO DIM_JUGADOR_POSICION (ID_JUGADOR, ID_POSICION, ES_POSICION_PRINCIPAL)
VALUES (@id_luiz_gustavo, (SELECT ID_POSICION FROM DIM_POSICION WHERE NOMBRE = 'CB'), TRUE);

-- ========================================
-- LATERALES IZQUIERDOS
-- ========================================

-- Luciano Juba (LB) - 29/08/1999 (26 años) - Brasil - 11.00 mill. € - #25
INSERT INTO DIM_JUGADOR (NOMBRE_COMPLETO, APODO, FECHA_NACIMIENTO, PLAYER_ID_FBR)
VALUES ('Luciano Juba', 'Luciano Juba', '1999-08-29', NULL);
SET @id_juba = LAST_INSERT_ID();

INSERT IGNORE INTO DIM_JUGADOR_PAIS (ID_JUGADOR, ID_PAIS, ES_PAIS_PRIMARIO)
VALUES (@id_juba, (SELECT ID_PAIS FROM DIM_PAIS WHERE CODIGO_FIFA = 'BRA'), TRUE);

INSERT IGNORE INTO DIM_JUGADOR_POSICION (ID_JUGADOR, ID_POSICION, ES_POSICION_PRINCIPAL)
VALUES (@id_juba, (SELECT ID_POSICION FROM DIM_POSICION WHERE NOMBRE = 'LB'), TRUE);

-- Iago (LB) - 23/03/1997 (28 años) - Brasil - 3.50 mill. €
INSERT INTO DIM_JUGADOR (NOMBRE_COMPLETO, APODO, FECHA_NACIMIENTO, PLAYER_ID_FBR)
VALUES ('Iago', 'Iago', '1997-03-23', NULL);
SET @id_iago = LAST_INSERT_ID();

INSERT IGNORE INTO DIM_JUGADOR_PAIS (ID_JUGADOR, ID_PAIS, ES_PAIS_PRIMARIO)
VALUES (@id_iago, (SELECT ID_PAIS FROM DIM_PAIS WHERE CODIGO_FIFA = 'BRA'), TRUE);

INSERT IGNORE INTO DIM_JUGADOR_POSICION (ID_JUGADOR, ID_POSICION, ES_POSICION_PRINCIPAL)
VALUES (@id_iago, (SELECT ID_POSICION FROM DIM_POSICION WHERE NOMBRE = 'LB'), TRUE);

-- Matheus Bahia (LB) - 11/08/1999 (26 años) - Brasil - 3.00 mill. € - #66
INSERT INTO DIM_JUGADOR (NOMBRE_COMPLETO, APODO, FECHA_NACIMIENTO, PLAYER_ID_FBR)
VALUES ('Matheus Bahia', 'Matheus Bahia', '1999-08-11', NULL);
SET @id_matheus_bahia = LAST_INSERT_ID();

INSERT IGNORE INTO DIM_JUGADOR_PAIS (ID_JUGADOR, ID_PAIS, ES_PAIS_PRIMARIO)
VALUES (@id_matheus_bahia, (SELECT ID_PAIS FROM DIM_PAIS WHERE CODIGO_FIFA = 'BRA'), TRUE);

INSERT IGNORE INTO DIM_JUGADOR_POSICION (ID_JUGADOR, ID_POSICION, ES_POSICION_PRINCIPAL)
VALUES (@id_matheus_bahia, (SELECT ID_POSICION FROM DIM_POSICION WHERE NOMBRE = 'LB'), TRUE);

-- Zé Guilherme (LB) - 16/03/2005 (20 años) - Brasil - 400 mil € - #2
INSERT INTO DIM_JUGADOR (NOMBRE_COMPLETO, APODO, FECHA_NACIMIENTO, PLAYER_ID_FBR)
VALUES ('Zé Guilherme', 'Zé Guilherme', '2005-03-16', NULL);
SET @id_ze_guilherme = LAST_INSERT_ID();

INSERT IGNORE INTO DIM_JUGADOR_PAIS (ID_JUGADOR, ID_PAIS, ES_PAIS_PRIMARIO)
VALUES (@id_ze_guilherme, (SELECT ID_PAIS FROM DIM_PAIS WHERE CODIGO_FIFA = 'BRA'), TRUE);

INSERT IGNORE INTO DIM_JUGADOR_POSICION (ID_JUGADOR, ID_POSICION, ES_POSICION_PRINCIPAL)
VALUES (@id_ze_guilherme, (SELECT ID_POSICION FROM DIM_POSICION WHERE NOMBRE = 'LB'), TRUE);

-- ========================================
-- LATERALES DERECHOS
-- ========================================

-- Gilberto (RB) - 07/03/1993 (32 años) - Brasil - 2.50 mill. € - #31
INSERT INTO DIM_JUGADOR (NOMBRE_COMPLETO, APODO, FECHA_NACIMIENTO, PLAYER_ID_FBR)
VALUES ('Gilberto', 'Gilberto', '1993-03-07', NULL);
SET @id_gilberto = LAST_INSERT_ID();

INSERT IGNORE INTO DIM_JUGADOR_PAIS (ID_JUGADOR, ID_PAIS, ES_PAIS_PRIMARIO)
VALUES (@id_gilberto, (SELECT ID_PAIS FROM DIM_PAIS WHERE CODIGO_FIFA = 'BRA'), TRUE);

INSERT IGNORE INTO DIM_JUGADOR_POSICION (ID_JUGADOR, ID_POSICION, ES_POSICION_PRINCIPAL)
VALUES (@id_gilberto, (SELECT ID_POSICION FROM DIM_POSICION WHERE NOMBRE = 'RB'), TRUE);

-- Román Gómez (RB) - 14/07/2004 (21 años) - Argentina - 1.50 mill. € - #19
INSERT INTO DIM_JUGADOR (NOMBRE_COMPLETO, APODO, FECHA_NACIMIENTO, PLAYER_ID_FBR)
VALUES ('Román Gómez', 'Román Gómez', '2004-07-14', NULL);
SET @id_roman_gomez = LAST_INSERT_ID();

INSERT IGNORE INTO DIM_JUGADOR_PAIS (ID_JUGADOR, ID_PAIS, ES_PAIS_PRIMARIO)
VALUES (@id_roman_gomez, (SELECT ID_PAIS FROM DIM_PAIS WHERE CODIGO_FIFA = 'ARG'), TRUE);

INSERT IGNORE INTO DIM_JUGADOR_POSICION (ID_JUGADOR, ID_POSICION, ES_POSICION_PRINCIPAL)
VALUES (@id_roman_gomez, (SELECT ID_POSICION FROM DIM_POSICION WHERE NOMBRE = 'RB'), TRUE);

-- ========================================
-- PIVOTES / MEDIOCENTROS DEFENSIVOS
-- ========================================

-- Caio Alexandre (DM) - 24/02/1999 (26 años) - Brasil - 7.00 mill. € - #14
INSERT INTO DIM_JUGADOR (NOMBRE_COMPLETO, APODO, FECHA_NACIMIENTO, PLAYER_ID_FBR)
VALUES ('Caio Alexandre', 'Caio Alexandre', '1999-02-24', NULL);
SET @id_caio_alexandre = LAST_INSERT_ID();

INSERT IGNORE INTO DIM_JUGADOR_PAIS (ID_JUGADOR, ID_PAIS, ES_PAIS_PRIMARIO)
VALUES (@id_caio_alexandre, (SELECT ID_PAIS FROM DIM_PAIS WHERE CODIGO_FIFA = 'BRA'), TRUE);

INSERT IGNORE INTO DIM_JUGADOR_POSICION (ID_JUGADOR, ID_POSICION, ES_POSICION_PRINCIPAL)
VALUES (@id_caio_alexandre, (SELECT ID_POSICION FROM DIM_POSICION WHERE NOMBRE = 'DM'), TRUE);

-- Erick (DM) - 14/11/1997 (28 años) - Brasil - 4.00 mill. € - #26
INSERT INTO DIM_JUGADOR (NOMBRE_COMPLETO, APODO, FECHA_NACIMIENTO, PLAYER_ID_FBR)
VALUES ('Erick', 'Erick', '1997-11-14', NULL);
SET @id_erick_dm = LAST_INSERT_ID();

INSERT IGNORE INTO DIM_JUGADOR_PAIS (ID_JUGADOR, ID_PAIS, ES_PAIS_PRIMARIO)
VALUES (@id_erick_dm, (SELECT ID_PAIS FROM DIM_PAIS WHERE CODIGO_FIFA = 'BRA'), TRUE);

INSERT IGNORE INTO DIM_JUGADOR_POSICION (ID_JUGADOR, ID_POSICION, ES_POSICION_PRINCIPAL)
VALUES (@id_erick_dm, (SELECT ID_POSICION FROM DIM_POSICION WHERE NOMBRE = 'DM'), TRUE);

-- Nicolás Acevedo (DM) - 14/04/1999 (26 años) - Uruguay - 4.00 mill. € - #5
INSERT INTO DIM_JUGADOR (NOMBRE_COMPLETO, APODO, FECHA_NACIMIENTO, PLAYER_ID_FBR)
VALUES ('Nicolás Acevedo', 'Nicolás Acevedo', '1999-04-14', NULL);
SET @id_acevedo = LAST_INSERT_ID();

INSERT IGNORE INTO DIM_JUGADOR_PAIS (ID_JUGADOR, ID_PAIS, ES_PAIS_PRIMARIO)
VALUES (@id_acevedo, (SELECT ID_PAIS FROM DIM_PAIS WHERE CODIGO_FIFA = 'URU'), TRUE);

INSERT IGNORE INTO DIM_JUGADOR_POSICION (ID_JUGADOR, ID_POSICION, ES_POSICION_PRINCIPAL)
VALUES (@id_acevedo, (SELECT ID_POSICION FROM DIM_POSICION WHERE NOMBRE = 'DM'), TRUE);

-- Rezende (DM) - 02/01/1995 (31 años) - Brasil - 800 mil € - #6
INSERT INTO DIM_JUGADOR (NOMBRE_COMPLETO, APODO, FECHA_NACIMIENTO, PLAYER_ID_FBR)
VALUES ('Rezende', 'Rezende', '1995-01-02', NULL);
SET @id_rezende = LAST_INSERT_ID();

INSERT IGNORE INTO DIM_JUGADOR_PAIS (ID_JUGADOR, ID_PAIS, ES_PAIS_PRIMARIO)
VALUES (@id_rezende, (SELECT ID_PAIS FROM DIM_PAIS WHERE CODIGO_FIFA = 'BRA'), TRUE);

INSERT IGNORE INTO DIM_JUGADOR_POSICION (ID_JUGADOR, ID_POSICION, ES_POSICION_PRINCIPAL)
VALUES (@id_rezende, (SELECT ID_POSICION FROM DIM_POSICION WHERE NOMBRE = 'DM'), TRUE);

-- ========================================
-- MEDIOCENTROS
-- ========================================

-- Jean Lucas (CM) - 22/06/1998 (27 años) - Brasil - 12.00 mill. € - #11
INSERT INTO DIM_JUGADOR (NOMBRE_COMPLETO, APODO, FECHA_NACIMIENTO, PLAYER_ID_FBR)
VALUES ('Jean Lucas', 'Jean Lucas', '1998-06-22', NULL);
SET @id_jean_lucas = LAST_INSERT_ID();

INSERT IGNORE INTO DIM_JUGADOR_PAIS (ID_JUGADOR, ID_PAIS, ES_PAIS_PRIMARIO)
VALUES (@id_jean_lucas, (SELECT ID_PAIS FROM DIM_PAIS WHERE CODIGO_FIFA = 'BRA'), TRUE);

INSERT IGNORE INTO DIM_JUGADOR_POSICION (ID_JUGADOR, ID_POSICION, ES_POSICION_PRINCIPAL)
VALUES (@id_jean_lucas, (SELECT ID_POSICION FROM DIM_POSICION WHERE NOMBRE = 'CM'), TRUE);

-- Rodrigo Nestor (CM) - 09/08/2000 (25 años) - Brasil - 7.00 mill. €
INSERT INTO DIM_JUGADOR (NOMBRE_COMPLETO, APODO, FECHA_NACIMIENTO, PLAYER_ID_FBR)
VALUES ('Rodrigo Nestor', 'Rodrigo Nestor', '2000-08-09', NULL);
SET @id_nestor = LAST_INSERT_ID();

INSERT IGNORE INTO DIM_JUGADOR_PAIS (ID_JUGADOR, ID_PAIS, ES_PAIS_PRIMARIO)
VALUES (@id_nestor, (SELECT ID_PAIS FROM DIM_PAIS WHERE CODIGO_FIFA = 'BRA'), TRUE);

INSERT IGNORE INTO DIM_JUGADOR_POSICION (ID_JUGADOR, ID_POSICION, ES_POSICION_PRINCIPAL)
VALUES (@id_nestor, (SELECT ID_POSICION FROM DIM_POSICION WHERE NOMBRE = 'CM'), TRUE);

-- Miqueias (CM) - 27/07/2001 (24 años) - Brasil - 250 mil € - #68
INSERT INTO DIM_JUGADOR (NOMBRE_COMPLETO, APODO, FECHA_NACIMIENTO, PLAYER_ID_FBR)
VALUES ('Miqueias', 'Miqueias', '2001-07-27', NULL);
SET @id_miqueias = LAST_INSERT_ID();

INSERT IGNORE INTO DIM_JUGADOR_PAIS (ID_JUGADOR, ID_PAIS, ES_PAIS_PRIMARIO)
VALUES (@id_miqueias, (SELECT ID_PAIS FROM DIM_PAIS WHERE CODIGO_FIFA = 'BRA'), TRUE);

INSERT IGNORE INTO DIM_JUGADOR_POSICION (ID_JUGADOR, ID_POSICION, ES_POSICION_PRINCIPAL)
VALUES (@id_miqueias, (SELECT ID_POSICION FROM DIM_POSICION WHERE NOMBRE = 'CM'), TRUE);

-- Jota (CM) - 06/02/2004 (22 años) - Brasil - #8
INSERT INTO DIM_JUGADOR (NOMBRE_COMPLETO, APODO, FECHA_NACIMIENTO, PLAYER_ID_FBR)
VALUES ('Jota', 'Jota', '2004-02-06', NULL);
SET @id_jota = LAST_INSERT_ID();

INSERT IGNORE INTO DIM_JUGADOR_PAIS (ID_JUGADOR, ID_PAIS, ES_PAIS_PRIMARIO)
VALUES (@id_jota, (SELECT ID_PAIS FROM DIM_PAIS WHERE CODIGO_FIFA = 'BRA'), TRUE);

INSERT IGNORE INTO DIM_JUGADOR_POSICION (ID_JUGADOR, ID_POSICION, ES_POSICION_PRINCIPAL)
VALUES (@id_jota, (SELECT ID_POSICION FROM DIM_POSICION WHERE NOMBRE = 'CM'), TRUE);

-- ========================================
-- MEDIOCENTROS OFENSIVOS
-- ========================================

-- Cauly (AM) - 15/09/1995 (30 años) - Brasil/Alemania - 4.50 mill. € - #10
INSERT INTO DIM_JUGADOR (NOMBRE_COMPLETO, APODO, FECHA_NACIMIENTO, PLAYER_ID_FBR)
VALUES ('Cauly', 'Cauly', '1995-09-15', NULL);
SET @id_cauly = LAST_INSERT_ID();

INSERT IGNORE INTO DIM_JUGADOR_PAIS (ID_JUGADOR, ID_PAIS, ES_PAIS_PRIMARIO)
VALUES (@id_cauly, (SELECT ID_PAIS FROM DIM_PAIS WHERE CODIGO_FIFA = 'BRA'), TRUE);
INSERT IGNORE INTO DIM_JUGADOR_PAIS (ID_JUGADOR, ID_PAIS, ES_PAIS_PRIMARIO)
VALUES (@id_cauly, (SELECT ID_PAIS FROM DIM_PAIS WHERE CODIGO_FIFA = 'GER'), FALSE);

INSERT IGNORE INTO DIM_JUGADOR_POSICION (ID_JUGADOR, ID_POSICION, ES_POSICION_PRINCIPAL)
VALUES (@id_cauly, (SELECT ID_POSICION FROM DIM_POSICION WHERE NOMBRE = 'AM'), TRUE);

-- Everton Ribeiro (AM) - 10/04/1989 (36 años) - Brasil - 1.20 mill. € - #16
INSERT INTO DIM_JUGADOR (NOMBRE_COMPLETO, APODO, FECHA_NACIMIENTO, PLAYER_ID_FBR)
VALUES ('Everton Ribeiro', 'Everton Ribeiro', '1989-04-10', NULL);
SET @id_everton_ribeiro = LAST_INSERT_ID();

INSERT IGNORE INTO DIM_JUGADOR_PAIS (ID_JUGADOR, ID_PAIS, ES_PAIS_PRIMARIO)
VALUES (@id_everton_ribeiro, (SELECT ID_PAIS FROM DIM_PAIS WHERE CODIGO_FIFA = 'BRA'), TRUE);

INSERT IGNORE INTO DIM_JUGADOR_POSICION (ID_JUGADOR, ID_POSICION, ES_POSICION_PRINCIPAL)
VALUES (@id_everton_ribeiro, (SELECT ID_POSICION FROM DIM_POSICION WHERE NOMBRE = 'AM'), TRUE);

-- ========================================
-- EXTREMOS IZQUIERDOS
-- ========================================

-- Erick Pulga (LW) - 02/10/2000 (25 años) - Brasil - 11.00 mill. € - #52
INSERT INTO DIM_JUGADOR (NOMBRE_COMPLETO, APODO, FECHA_NACIMIENTO, PLAYER_ID_FBR)
VALUES ('Erick Pulga', 'Erick Pulga', '2000-10-02', NULL);
SET @id_erick_pulga = LAST_INSERT_ID();

INSERT IGNORE INTO DIM_JUGADOR_PAIS (ID_JUGADOR, ID_PAIS, ES_PAIS_PRIMARIO)
VALUES (@id_erick_pulga, (SELECT ID_PAIS FROM DIM_PAIS WHERE CODIGO_FIFA = 'BRA'), TRUE);

INSERT IGNORE INTO DIM_JUGADOR_POSICION (ID_JUGADOR, ID_POSICION, ES_POSICION_PRINCIPAL)
VALUES (@id_erick_pulga, (SELECT ID_POSICION FROM DIM_POSICION WHERE NOMBRE = 'LW'), TRUE);

-- Ruan Pablo (LW) - 23/07/2008 (17 años) - Brasil - 5.00 mill. € - #15
INSERT INTO DIM_JUGADOR (NOMBRE_COMPLETO, APODO, FECHA_NACIMIENTO, PLAYER_ID_FBR)
VALUES ('Ruan Pablo', 'Ruan Pablo', '2008-07-23', NULL);
SET @id_ruan_pablo = LAST_INSERT_ID();

INSERT IGNORE INTO DIM_JUGADOR_PAIS (ID_JUGADOR, ID_PAIS, ES_PAIS_PRIMARIO)
VALUES (@id_ruan_pablo, (SELECT ID_PAIS FROM DIM_PAIS WHERE CODIGO_FIFA = 'BRA'), TRUE);

INSERT IGNORE INTO DIM_JUGADOR_POSICION (ID_JUGADOR, ID_POSICION, ES_POSICION_PRINCIPAL)
VALUES (@id_ruan_pablo, (SELECT ID_POSICION FROM DIM_POSICION WHERE NOMBRE = 'LW'), TRUE);

-- Michel Araújo (LW) - 28/09/1996 (29 años) - Uruguay - 2.50 mill. € - #23
INSERT INTO DIM_JUGADOR (NOMBRE_COMPLETO, APODO, FECHA_NACIMIENTO, PLAYER_ID_FBR)
VALUES ('Michel Araújo', 'Michel Araújo', '1996-09-28', NULL);
SET @id_michel_araujo = LAST_INSERT_ID();

INSERT IGNORE INTO DIM_JUGADOR_PAIS (ID_JUGADOR, ID_PAIS, ES_PAIS_PRIMARIO)
VALUES (@id_michel_araujo, (SELECT ID_PAIS FROM DIM_PAIS WHERE CODIGO_FIFA = 'URU'), TRUE);

INSERT IGNORE INTO DIM_JUGADOR_POSICION (ID_JUGADOR, ID_POSICION, ES_POSICION_PRINCIPAL)
VALUES (@id_michel_araujo, (SELECT ID_POSICION FROM DIM_POSICION WHERE NOMBRE = 'LW'), TRUE);

-- Mateo Sanabria (LW) - 31/03/2004 (21 años) - Argentina/Italia - 600 mil € - #99
INSERT INTO DIM_JUGADOR (NOMBRE_COMPLETO, APODO, FECHA_NACIMIENTO, PLAYER_ID_FBR)
VALUES ('Mateo Sanabria', 'Mateo Sanabria', '2004-03-31', NULL);
SET @id_mateo_sanabria = LAST_INSERT_ID();

INSERT IGNORE INTO DIM_JUGADOR_PAIS (ID_JUGADOR, ID_PAIS, ES_PAIS_PRIMARIO)
VALUES (@id_mateo_sanabria, (SELECT ID_PAIS FROM DIM_PAIS WHERE CODIGO_FIFA = 'ARG'), TRUE);
INSERT IGNORE INTO DIM_JUGADOR_PAIS (ID_JUGADOR, ID_PAIS, ES_PAIS_PRIMARIO)
VALUES (@id_mateo_sanabria, (SELECT ID_PAIS FROM DIM_PAIS WHERE CODIGO_FIFA = 'ITA'), FALSE);

INSERT IGNORE INTO DIM_JUGADOR_POSICION (ID_JUGADOR, ID_POSICION, ES_POSICION_PRINCIPAL)
VALUES (@id_mateo_sanabria, (SELECT ID_POSICION FROM DIM_POSICION WHERE NOMBRE = 'LW'), TRUE);

-- ========================================
-- EXTREMOS DERECHOS
-- ========================================

-- Cristian Olivera (RW) - 17/04/2002 (23 años) - Uruguay - 5.00 mill. € - #7
INSERT INTO DIM_JUGADOR (NOMBRE_COMPLETO, APODO, FECHA_NACIMIENTO, PLAYER_ID_FBR)
VALUES ('Cristian Olivera', 'Cristian Olivera', '2002-04-17', NULL);
SET @id_olivera = LAST_INSERT_ID();

INSERT IGNORE INTO DIM_JUGADOR_PAIS (ID_JUGADOR, ID_PAIS, ES_PAIS_PRIMARIO)
VALUES (@id_olivera, (SELECT ID_PAIS FROM DIM_PAIS WHERE CODIGO_FIFA = 'URU'), TRUE);

INSERT IGNORE INTO DIM_JUGADOR_POSICION (ID_JUGADOR, ID_POSICION, ES_POSICION_PRINCIPAL)
VALUES (@id_olivera, (SELECT ID_POSICION FROM DIM_POSICION WHERE NOMBRE = 'RW'), TRUE);

-- Ademir (RW) - 16/02/1995 (30 años) - Brasil - 1.50 mill. € - #12
INSERT INTO DIM_JUGADOR (NOMBRE_COMPLETO, APODO, FECHA_NACIMIENTO, PLAYER_ID_FBR)
VALUES ('Ademir', 'Ademir', '1995-02-16', NULL);
SET @id_ademir = LAST_INSERT_ID();

INSERT IGNORE INTO DIM_JUGADOR_PAIS (ID_JUGADOR, ID_PAIS, ES_PAIS_PRIMARIO)
VALUES (@id_ademir, (SELECT ID_PAIS FROM DIM_PAIS WHERE CODIGO_FIFA = 'BRA'), TRUE);

INSERT IGNORE INTO DIM_JUGADOR_POSICION (ID_JUGADOR, ID_POSICION, ES_POSICION_PRINCIPAL)
VALUES (@id_ademir, (SELECT ID_POSICION FROM DIM_POSICION WHERE NOMBRE = 'RW'), TRUE);

-- ========================================
-- DELANTEROS CENTRO
-- ========================================

-- Willian José (CF) - 23/11/1991 (34 años) - Brasil/España - 1.40 mill. € - #27
INSERT INTO DIM_JUGADOR (NOMBRE_COMPLETO, APODO, FECHA_NACIMIENTO, PLAYER_ID_FBR)
VALUES ('Willian José', 'Willian José', '1991-11-23', NULL);
SET @id_willian_jose = LAST_INSERT_ID();

INSERT IGNORE INTO DIM_JUGADOR_PAIS (ID_JUGADOR, ID_PAIS, ES_PAIS_PRIMARIO)
VALUES (@id_willian_jose, (SELECT ID_PAIS FROM DIM_PAIS WHERE CODIGO_FIFA = 'BRA'), TRUE);
INSERT IGNORE INTO DIM_JUGADOR_PAIS (ID_JUGADOR, ID_PAIS, ES_PAIS_PRIMARIO)
VALUES (@id_willian_jose, (SELECT ID_PAIS FROM DIM_PAIS WHERE CODIGO_FIFA = 'ESP'), FALSE);

INSERT IGNORE INTO DIM_JUGADOR_POSICION (ID_JUGADOR, ID_POSICION, ES_POSICION_PRINCIPAL)
VALUES (@id_willian_jose, (SELECT ID_POSICION FROM DIM_POSICION WHERE NOMBRE = 'CF'), TRUE);

-- Everaldo (CF) - 05/07/1991 (34 años) - Brasil - 400 mil € - #89
INSERT INTO DIM_JUGADOR (NOMBRE_COMPLETO, APODO, FECHA_NACIMIENTO, PLAYER_ID_FBR)
VALUES ('Everaldo', 'Everaldo', '1991-07-05', NULL);
SET @id_everaldo = LAST_INSERT_ID();

INSERT IGNORE INTO DIM_JUGADOR_PAIS (ID_JUGADOR, ID_PAIS, ES_PAIS_PRIMARIO)
VALUES (@id_everaldo, (SELECT ID_PAIS FROM DIM_PAIS WHERE CODIGO_FIFA = 'BRA'), TRUE);

INSERT IGNORE INTO DIM_JUGADOR_POSICION (ID_JUGADOR, ID_POSICION, ES_POSICION_PRINCIPAL)
VALUES (@id_everaldo, (SELECT ID_POSICION FROM DIM_POSICION WHERE NOMBRE = 'CF'), TRUE);

-- Dell (CF) - 09/06/2008 (17 años) - Brasil
INSERT INTO DIM_JUGADOR (NOMBRE_COMPLETO, APODO, FECHA_NACIMIENTO, PLAYER_ID_FBR)
VALUES ('Dell', 'Dell', '2008-06-09', NULL);
SET @id_dell = LAST_INSERT_ID();

INSERT IGNORE INTO DIM_JUGADOR_PAIS (ID_JUGADOR, ID_PAIS, ES_PAIS_PRIMARIO)
VALUES (@id_dell, (SELECT ID_PAIS FROM DIM_PAIS WHERE CODIGO_FIFA = 'BRA'), TRUE);

INSERT IGNORE INTO DIM_JUGADOR_POSICION (ID_JUGADOR, ID_POSICION, ES_POSICION_PRINCIPAL)
VALUES (@id_dell, (SELECT ID_POSICION FROM DIM_POSICION WHERE NOMBRE = 'CF'), TRUE);

-- ========================================
-- VERIFICACIÓN FINAL
-- ========================================

SELECT 'Jugadores de Bahia agregados exitosamente' as mensaje;

SELECT
  COUNT(*) as total_jugadores_bahia,
  (SELECT COUNT(*) FROM DIM_JUGADOR WHERE NOMBRE_COMPLETO IN (
    'João Paulo', 'Ronaldo', 'Santiago Ramos Mingo', 'Gabriel Xavier', 'Kanu',
    'David Duarte', 'Luiz Gustavo', 'Luciano Juba', 'Iago', 'Matheus Bahia',
    'Zé Guilherme', 'Gilberto', 'Román Gómez', 'Caio Alexandre', 'Erick',
    'Nicolás Acevedo', 'Rezende', 'Jean Lucas', 'Rodrigo Nestor', 'Miqueias',
    'Jota', 'Cauly', 'Everton Ribeiro', 'Erick Pulga', 'Ruan Pablo',
    'Michel Araújo', 'Mateo Sanabria', 'Cristian Olivera', 'Ademir',
    'Willian José', 'Everaldo', 'Dell'
  )) as jugadores_insertados
FROM DUAL;
