-- ACTUALIZACIÓN DEL ESQUEMA DE BASE DE DATOS PARA INTEGRACIÓN CON FBR API
-- Este script modifica las tablas existentes para incluir los campos necesarios

USE MP_DATA_DEV;

-- 1. MODIFICAR DIM_JUGADOR para incluir PLAYER_ID_FBR como clave única
ALTER TABLE DIM_JUGADOR 
ADD COLUMN PLAYER_ID_FBR VARCHAR(20) AFTER ID_JUGADOR;

-- Agregar índice único para PLAYER_ID_FBR
ALTER TABLE DIM_JUGADOR 
ADD UNIQUE KEY uk_player_id_fbr (PLAYER_ID_FBR);

-- Agregar campos adicionales a DIM_JUGADOR
ALTER TABLE DIM_JUGADOR 
ADD COLUMN ALTURA_CM DECIMAL(5,2) AFTER FECHA_NACIMIENTO,
ADD COLUMN PESO_KG DECIMAL(5,2) AFTER ALTURA_CM,
ADD COLUMN PIE_DOMINANTE VARCHAR(10) AFTER PESO_KG,
ADD COLUMN CIUDAD_NACIMIENTO VARCHAR(100) AFTER PIE_DOMINANTE,
ADD COLUMN SALARIO VARCHAR(100) AFTER CIUDAD_NACIMIENTO,
ADD COLUMN URL_FOTO TEXT AFTER SALARIO;

-- 2. MODIFICAR DIM_PAIS para incluir nombre del país completo
ALTER TABLE DIM_PAIS 
ADD COLUMN NOMBRE_COMPLETO VARCHAR(100) AFTER NOMBRE;

-- 3. AGREGAR TABLA PARA EQUIPOS (necesaria para las relaciones)
CREATE TABLE IF NOT EXISTS DIM_EQUIPO_TEMPORADA (
  ID_EQUIPO_TEMPORADA INT(11) NOT NULL AUTO_INCREMENT,
  ID_EQUIPO INT(11) NOT NULL,
  ID_TORNEO INT(11) NOT NULL,
  TEMPORADA VARCHAR(9) NOT NULL,
  PRIMARY KEY (ID_EQUIPO_TEMPORADA),
  UNIQUE KEY uk_equipo_torneo_temporada (ID_EQUIPO, ID_TORNEO, TEMPORADA),
  KEY idx_equipo (ID_EQUIPO),
  KEY idx_torneo (ID_TORNEO),
  CONSTRAINT fk_equipo_temporada_equipo FOREIGN KEY (ID_EQUIPO) REFERENCES DIM_EQUIPO (ID_EQUIPO),
  CONSTRAINT fk_equipo_temporada_torneo FOREIGN KEY (ID_TORNEO) REFERENCES DIM_TORNEO (ID_TORNEO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- 4. AGREGAR TABLA PARA RELACIONAR JUGADORES CON EQUIPOS EN TEMPORADAS ESPECÍFICAS
-- (Esta tabla ya existe como DIM_TORNEO_JUGADOR, pero vamos a asegurar su estructura)

-- 5. MODIFICAR DIM_JUGADOR_POSICION para incluir información del roster
ALTER TABLE DIM_JUGADOR_POSICION 
ADD COLUMN ES_POSICION_ROSTER TINYINT(1) DEFAULT 0 AFTER ES_POSICION_PRINCIPAL,
ADD COLUMN TEMPORADA VARCHAR(9) AFTER ES_POSICION_ROSTER;

-- 6. CREAR TABLA PARA ESTADÍSTICAS DEL ROSTER (información específica de la temporada)
CREATE TABLE IF NOT EXISTS HECHOS_JUGADOR_ROSTER (
  ID_JUGADOR_ROSTER INT(11) NOT NULL AUTO_INCREMENT,
  ID_JUGADOR INT(11) NOT NULL,
  ID_EQUIPO INT(11) NOT NULL,
  ID_TORNEO INT(11) NOT NULL,
  TEMPORADA VARCHAR(9) NOT NULL,
  EDAD_ROSTER INT(11),
  PARTIDOS_JUGADOS INT(11) DEFAULT 0,
  PARTIDOS_TITULAR INT(11) DEFAULT 0,
  POSICION_PRINCIPAL VARCHAR(10),
  FECHA_REGISTRO DATETIME DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (ID_JUGADOR_ROSTER),
  UNIQUE KEY uk_jugador_equipo_torneo_temporada (ID_JUGADOR, ID_EQUIPO, ID_TORNEO, TEMPORADA),
  KEY idx_jugador_roster (ID_JUGADOR),
  KEY idx_equipo_roster (ID_EQUIPO),
  KEY idx_torneo_roster (ID_TORNEO),
  CONSTRAINT fk_jugador_roster_jugador FOREIGN KEY (ID_JUGADOR) REFERENCES DIM_JUGADOR (ID_JUGADOR),
  CONSTRAINT fk_jugador_roster_equipo FOREIGN KEY (ID_EQUIPO) REFERENCES DIM_EQUIPO (ID_EQUIPO),
  CONSTRAINT fk_jugador_roster_torneo FOREIGN KEY (ID_TORNEO) REFERENCES DIM_TORNEO (ID_TORNEO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- 7. INSERTAR POSICIONES BÁSICAS EN DIM_POSICION (si no existen)
INSERT IGNORE INTO DIM_POSICION (NOMBRE, DESCRIPCION) VALUES
('GK', 'Portero - Goalkeeper'),
('DF', 'Defensa - Defender'),
('MF', 'Mediocampista - Midfielder'), 
('FW', 'Delantero - Forward'),
('CB', 'Defensa Central - Centre Back'),
('FB', 'Lateral - Full Back'),
('CM', 'Mediocampista Central - Central Midfielder'),
('AM', 'Mediocampista Ofensivo - Attacking Midfielder');

-- 8. INSERTAR PAÍSES BÁSICOS EN DIM_PAIS (basado en el análisis del CSV)
INSERT IGNORE INTO DIM_PAIS (NOMBRE, CODIGO_FIFA, NOMBRE_COMPLETO) VALUES
('ARG', 'ARG', 'Argentina'),
('CHI', 'CHI', 'Chile'),
('COL', 'COL', 'Colombia'),
('PAR', 'PAR', 'Paraguay'),
('ECU', 'ECU', 'Ecuador');

-- 9. CREAR FUNCIÓN AUXILIAR PARA NORMALIZAR NOMBRES
DELIMITER //
DROP FUNCTION IF EXISTS NORMALIZE_NAME//
CREATE FUNCTION NORMALIZE_NAME(input_name VARCHAR(255))
RETURNS VARCHAR(255)
DETERMINISTIC
READS SQL DATA
BEGIN
    DECLARE normalized_name VARCHAR(255);
    
    -- Convertir a mayúsculas y limpiar espacios
    SET normalized_name = UPPER(TRIM(input_name));
    
    -- Reemplazar múltiples espacios con uno solo
    WHILE LOCATE('  ', normalized_name) > 0 DO
        SET normalized_name = REPLACE(normalized_name, '  ', ' ');
    END WHILE;
    
    RETURN normalized_name;
END//
DELIMITER ;

-- 10. MOSTRAR ESTRUCTURA ACTUALIZADA
SELECT 'ESTRUCTURA ACTUALIZADA DE DIM_JUGADOR:' as INFO;
DESCRIBE DIM_JUGADOR;

SELECT 'ESTRUCTURA ACTUALIZADA DE DIM_PAIS:' as INFO;
DESCRIBE DIM_PAIS;

SELECT 'POSICIONES DISPONIBLES:' as INFO;
SELECT * FROM DIM_POSICION ORDER BY NOMBRE;

SELECT 'PAÍSES DISPONIBLES:' as INFO;
SELECT * FROM DIM_PAIS ORDER BY CODIGO_FIFA;